[package]
name = "pomocop"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15.0"
tap = "1.0.1"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
indoc = "1.0.3"

[dependencies.poise]
git = "https://github.com/kangalioo/poise"
branch = "master"

[dependencies.tokio]
version = "1.11.0"
features = [ "rt-multi-thread" ]
