[package]
name = "tomat"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15.0"
poise = { git = "https://github.com/kangalioo/poise", branch = "master" }
tap = "1.0.1"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
